### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by rudnypc** [Scrip7/fmovies-crawler#1]
Hi,

First I must to say thanks for your system.

I would like to know if can I retrieve the subtitles url

**Comment by Scrip7** [comment]
Hey there,
This project is not finished yet, and I still need to focus on retrieving video details cause they have higher priority.

Once I finished other parts, I can implement the subtitle fetching feature too.
Meanwhile, If you are in a hurry, PRs are welcome :)
