### ISSUE TITLE
Stream url is associated with localhost.

### ISSUE THREAD

**Issue by syednytro** [Scrip7/fmovies-crawler#2]
Hello, nice work. Really appreciated.
Would you mind telling me why stream url is associated with localhost. shouldn't it be connected to real url?

**Comment by Scrip7** [comment]
Hey, thanks :)

So basically while I was working on this project,
I noticed the returning stream URL from the FMovies website is limited to the requester's IP address,
and the returning stream URL **can not** be opened and viewed by other users who have different IP addresses as clients!

That was a problem and my goal was to expose an HTTP API so everyone can retrieve the stream URL and the IP limitation.

So, I reversed proxied the returning stream URL website by using an `openresty` Docker instance and solved this issue.
https://github.com/Scrip7/fmovies-crawler/blob/main/docker-compose.yml#L60
https://github.com/Scrip7/fmovies-crawler/blob/main/nginx/nginx.conf#L26

If you're wondering where I replace the stream URL:
https://github.com/Scrip7/fmovies-crawler/blob/main/src/video/video.service.ts#L44

If you're running the app on a server and want to replace the `localhost` with an actual IP address or domain,
consider setting the `BASE_URI` variable in the `.env` file.
https://github.com/Scrip7/fmovies-crawler/blob/main/.env.example#L7

Let me know if this is still an issue 😃
